import Head from 'next/head'
import Link from 'next/link'

export default function Home({ comments }) {
  return (
    <>
      <Head>
        <title>Next Js API fetching</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className='grid '>
        <div className='bg-emerald-300 p-2'>
          {comments?.map((comment) => {
            return <div className='space-y-1 border border-gray-600 rounded-lg p-2 m-2 text-center'>
              <h2>ID: {comment?.id}</h2>
              <h2 className='text-2xl font-medium'>Name: {comment?.name}</h2>
              <Link href={`/comments/${comment?.id}`}>
                <button className='bg-lime-600 p-2 rounded-md'>See Details</button>
              </Link>
              
            </div>
          })}
        </div>
      </section>
    </>
  )
}
export const getStaticProps = async () => {
  const response = await fetch("https://jsonplaceholder.typicode.com/comments?_limit=10")
  const comments = await response.json()
  return {
    props: {
      comments
    }
  }
}